language: python
python:
  - "2.7"
  - "3.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install pillow
# command to run tests
script: python test.py